version: '3'

networks:
  backend:

volumes:
  task-python-test:

services:
  task1:
    build:
      context: ./python-daemon
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - task-python-test:/python-daemon
    environment:
      ID_APP: 1
      URL_SERVER: http://server:5000
    # restart: always
  task2:
    build:
      context: ./python-daemon
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - task-python-test:/python-daemon
    environment:
      ID_APP: 2
      URL_SERVER: http://server:5000
  server:
    build:
      context: ./api-flask
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - task-python-test:/api-flask
    ports:
    - "9090:5000"
