version: '3'

volumes:
  task-python-test:

services:
  task:
    image: python:3.9-alpine
    build:
      context: python-daemon
      dockerfile: python-daemon/Dockerfile
    volumes:
      - task-python-test:/app

